/**
 * Enhanced Template Configs
 * Additions:
 * - Locked color palette presets per template
 * - Gradient fade overlay type
 * - Card edge treatment presets (hard / soft / feathered / shadow-only)
 * - Per-font letter-spacing baked into presets
 */

// ─── Font Presets ─────────────────────────────────────────────────────────────
const FONT_PRESETS = {
  manrope_inter: {
    heading: "'Manrope', sans-serif",
    body:    "'Inter', sans-serif",
    headingWeight: 800,
    bodyWeight:    400,
    headingTracking: '-0.02em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.10em',
  },
  playfair_inter: {
    heading: "'Playfair Display', serif",
    body:    "'Inter', sans-serif",
    headingWeight: 700,
    bodyWeight:    400,
    headingTracking: '-0.03em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.08em',
  },
  jakarta_dm: {
    heading: "'Plus Jakarta Sans', sans-serif",
    body:    "'DM Sans', sans-serif",
    headingWeight: 700,
    bodyWeight:    400,
    headingTracking: '-0.01em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.10em',
  },
  cormorant_manrope: {
    heading: "'Cormorant Garamond', serif",
    body:    "'Manrope', sans-serif",
    headingWeight: 600,
    bodyWeight:    500,
    headingTracking: '0.01em',
    bodyTracking:    '0em',
    altCapsTracking: '0.12em',
  },
  outfit_inter: {
    heading: "'Outfit', sans-serif",
    body:    "'Inter', sans-serif",
    headingWeight: 800,
    bodyWeight:    400,
    headingTracking: '-0.02em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.10em',
  },
};

// ─── Color Palette Presets ────────────────────────────────────────────────────
const COLOR_PALETTES = {
  pure_white:  { bg: '#ffffff',  text: '#111111', sub: '#444444', accent: '#111111' },
  off_white:   { bg: '#FAFAF8',  text: '#1a1a1a', sub: '#555555', accent: '#1a1a1a' },
  warm_cream:  { bg: '#F5F0E8',  text: '#2d1b00', sub: '#6b4c2a', accent: '#4a3000' },
  dark_ink:    { bg: '#111111',  text: '#f5f5f0', sub: '#aaaaaa', accent: '#e8e8e0' },
  charcoal:    { bg: '#1a1a2e',  text: '#f0f0f5', sub: '#9090a8', accent: '#a78bfa' },
};

// ─── Overlay Types ────────────────────────────────────────────────────────────
const OVERLAY_TYPES = {
  none:               { type: 'none',    opacity: 0 },
  translucent_white:  { type: 'sheet',   bg: 'rgba(255,255,255,0.82)',  blur: '8px',  edge: 'soft',      radius: '4px' },
  cream_card:         { type: 'card',    bg: 'rgba(253,248,240,0.92)',  blur: '4px',  edge: 'soft',      radius: '12px' },
  lower_third:        { type: 'lower',   bg: 'rgba(255,255,255,0.90)',  blur: '6px',  edge: 'hard',      radius: '0px' },
  subtle_fade:        { type: 'fade',    bg: 'linear-gradient(to top, rgba(0,0,0,0.72) 0%, transparent 58%)', blur: '0px', edge: 'none' },
  gradient_cream:     { type: 'fade',    bg: 'linear-gradient(to top, rgba(245,240,232,0.95) 0%, rgba(245,240,232,0.60) 40%, transparent 70%)', blur: '0px', edge: 'none' },
  gradient_dark:      { type: 'fade',    bg: 'linear-gradient(to top, rgba(0,0,0,0.88) 0%, rgba(0,0,0,0.45) 45%, transparent 72%)', blur: '0px', edge: 'none' },
  gradient_top:       { type: 'fade',    bg: 'linear-gradient(to bottom, rgba(0,0,0,0.65) 0%, rgba(0,0,0,0.20) 45%, transparent 70%)', blur: '0px', edge: 'none' },
  soft_panel:         { type: 'panel',   bg: 'rgba(255,255,255,0.75)',  blur: '12px', edge: 'soft',      radius: '20px' },
  dark_panel:         { type: 'panel',   bg: 'rgba(10,10,10,0.72)',     blur: '6px',  edge: 'soft',      radius: '16px' },
  luxury_cream:       { type: 'sheet',   bg: 'rgba(250,246,238,0.88)',  blur: '6px',  edge: 'feathered', radius: '0px' },
};

// ─── Template Families ────────────────────────────────────────────────────────
const TEMPLATE_FAMILIES = {

  upper_third_overlay: {
    id: 'upper_third_overlay',
    name: 'Upper Third Direct Overlay',
    description: 'Bold text placed in the upper third of the image',
    fontPreset: 'manrope_inter',
    overlay: 'gradient_top',
    colorPalette: null,      // null = auto from analysis
    textColor: '#ffffff',
    textPosition: 'upper',
    textAlign: 'left',
    maxTitleWidth: '75%',
    titleSizeMin: 38,
    titleSizeMax: 88,
    padding: { x: 60, y: 80 },
    textShadow: '0 2px 24px rgba(0,0,0,0.55)',
    gradientOverlay: null,
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'top-right',
    suitableFor: ['clean_top', 'light_top', 'dark_top', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 48,
  },

  top_middle_headline: {
    id: 'top_middle_headline',
    name: 'Top-Middle Narrow Headline',
    description: 'Centered narrow headline near the top',
    fontPreset: 'playfair_inter',
    overlay: 'gradient_top',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'upper-center',
    textAlign: 'center',
    maxTitleWidth: '60%',
    titleSizeMin: 32,
    titleSizeMax: 82,
    padding: { x: 80, y: 90 },
    textShadow: '0 4px 32px rgba(0,0,0,0.6)',
    gradientOverlay: null,
    showHRule: true,
    titleScale: 1.05,
    lineHeightBoost: 0.03,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['clean_top', 'minimal'],
    avoidWhen: ['busy_top', 'text_heavy'],
    safeMinPaddingPx: 48,
  },

  center_white_sheet: {
    id: 'center_white_sheet',
    name: 'Center Translucent White Sheet',
    description: 'Frosted glass card centered on image',
    fontPreset: 'jakarta_dm',
    overlay: 'translucent_white',
    colorPalette: 'pure_white',
    textColor: '#1a1a2e',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '80%',
    titleSizeMin: 42,
    titleSizeMax: 72,
    padding: { x: 60, y: 50 },
    textShadow: 'none',
    gradientOverlay: null,
    overlayWidth: '78%',
    overlayPaddingX: 48,
    overlayPaddingY: 52,
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'overlay-top',
    suitableFor: ['any', 'busy_center', 'colorful'],
    avoidWhen: [],
    safeMinPaddingPx: 48,
  },

  lower_third_card: {
    id: 'lower_third_card',
    name: 'Lower Third White Card',
    description: 'Clean card anchored to the bottom third',
    fontPreset: 'jakarta_dm',
    overlay: 'lower_third',
    colorPalette: 'off_white',
    textColor: '#111827',
    textPosition: 'lower',
    textAlign: 'left',
    maxTitleWidth: '85%',
    titleSizeMin: 40,
    titleSizeMax: 68,
    padding: { x: 48, y: 44 },
    textShadow: 'none',
    gradientOverlay: null,
    overlayHeight: '42%',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'card-top',
    suitableFor: ['clean_top', 'any'],
    avoidWhen: ['busy_bottom'],
    safeMinPaddingPx: 48,
  },

  left_editorial_column: {
    id: 'left_editorial_column',
    name: 'Left Editorial Column',
    description: 'Vertical card on the left with editorial styling',
    fontPreset: 'cormorant_manrope',
    overlay: 'cream_card',
    colorPalette: 'warm_cream',
    textColor: '#1c1205',
    textPosition: 'left',
    textAlign: 'left',
    maxTitleWidth: '94%',
    titleSizeMin: 44,
    titleSizeMax: 76,
    padding: { x: 42, y: 48 },
    textShadow: 'none',
    gradientOverlay: null,
    columnWidth: '56%',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'column-top',
    suitableFor: ['clean_right', 'portrait_subjects', 'warm_tones'],
    avoidWhen: ['busy_left'],
    safeMinPaddingPx: 48,
  },

  floating_soft_panel: {
    id: 'floating_soft_panel',
    name: 'Floating Soft Panel',
    description: 'Glassmorphism floating panel with soft blur',
    fontPreset: 'outfit_inter',
    overlay: 'soft_panel',
    colorPalette: 'pure_white',
    textColor: '#0f172a',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '74%',
    titleSizeMin: 38,
    titleSizeMax: 66,
    padding: { x: 52, y: 48 },
    textShadow: 'none',
    gradientOverlay: null,
    panelWidth: '74%',
    panelRadius: '24px',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'panel-top',
    suitableFor: ['any', 'gradient', 'abstract'],
    avoidWhen: [],
    safeMinPaddingPx: 48,
  },

  premium_article_cover: {
    id: 'premium_article_cover',
    name: 'Premium Article Cover',
    description: 'Magazine-style full cover with dark gradient fade',
    fontPreset: 'playfair_inter',
    overlay: 'gradient_dark',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'lower',
    textAlign: 'left',
    maxTitleWidth: '80%',
    titleSizeMin: 42,
    titleSizeMax: 76,
    padding: { x: 64, y: 76 },
    textShadow: '0 2px 16px rgba(0,0,0,0.4)',
    gradientOverlay: null,
    showHRule: true,
    coverLiftPx: 58,
    lineHeightBoost: 0.04,
    titleScale: 1.08,
    ctaStyle: 'pill',
    badgePosition: 'top-left',
    suitableFor: ['dark_bottom', 'any'],
    avoidWhen: ['light_bottom'],
    safeMinPaddingPx: 48,
  },

  soft_magazine: {
    id: 'soft_magazine',
    name: 'Soft Magazine Layout',
    description: 'Airy layout with gradient cream overlay',
    fontPreset: 'cormorant_manrope',
    overlay: 'gradient_cream',
    colorPalette: 'warm_cream',
    textColor: '#2d1b00',
    textPosition: 'lower-center',
    textAlign: 'center',
    maxTitleWidth: '82%',
    titleSizeMin: 38,
    titleSizeMax: 68,
    padding: { x: 60, y: 56 },
    textShadow: 'none',
    gradientOverlay: null,
    overlayHeight: '48%',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'overlay-center-top',
    suitableFor: ['warm_tones', 'desk', 'linen', 'marble'],
    avoidWhen: ['dark_tones'],
    safeMinPaddingPx: 48,
  },

  luxury_desk_headline: {
    id: 'luxury_desk_headline',
    name: 'Luxury Desk Headline',
    description: 'Dark panel headline for luxury/editorial aesthetic',
    fontPreset: 'manrope_inter',
    overlay: 'dark_panel',
    colorPalette: 'dark_ink',
    textColor: '#f5f0e8',
    textPosition: 'upper-left',
    textAlign: 'left',
    maxTitleWidth: '78%',
    titleSizeMin: 40,
    titleSizeMax: 72,
    padding: { x: 52, y: 64 },
    textShadow: '0 2px 12px rgba(0,0,0,0.3)',
    gradientOverlay: null,
    panelWidth: '78%',
    panelRadius: '16px',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'panel-top-right',
    suitableFor: ['dark_luxury', 'dark_tones', 'marble', 'wood'],
    avoidWhen: ['light_tones'],
    safeMinPaddingPx: 48,
  },

  minimalist_gradient_poster: {
    id: 'minimalist_gradient_poster',
    name: 'Minimalist Gradient Poster',
    description: 'Centered bold text over a subtle gradient veil',
    fontPreset: 'outfit_inter',
    overlay: 'none',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '68%',
    titleSizeMin: 42,
    titleSizeMax: 78,
    padding: { x: 80, y: 80 },
    textShadow: '0 4px 40px rgba(0,0,0,0.5)',
    gradientOverlay: 'linear-gradient(135deg, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0.15) 50%, rgba(0,0,0,0.45) 100%)',
    showHRule: false,
    lineHeightBoost: 0.07,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['gradient', 'abstract', 'minimal', 'texture'],
    avoidWhen: [],
    safeMinPaddingPx: 80,
  },

  gradient_editorial: {
    id: 'gradient_editorial',
    name: 'Gradient Editorial',
    description: 'Lower gradient fade — the single most-used premium Pinterest technique',
    fontPreset: 'playfair_inter',
    overlay: 'gradient_dark',
    colorPalette: null,
    textColor: '#FAFAF8',
    textPosition: 'lower',
    textAlign: 'left',
    maxTitleWidth: '80%',
    titleSizeMin: 42,
    titleSizeMax: 74,
    padding: { x: 84, y: 84 },
    textShadow: '0 2px 20px rgba(0,0,0,0.45)',
    gradientOverlay: null,
    showHRule: true,
    coverLiftPx: 24,
    titleScale: 1.06,
    ctaStyle: 'pill',
    badgePosition: 'top-left',
    suitableFor: ['any', 'dark_bottom', 'portrait_subjects'],
    avoidWhen: [],
    safeMinPaddingPx: 48,
  },
};

// ─── Pin Sizes ────────────────────────────────────────────────────────────────
const PIN_SIZES = {
  standard:   { width: 1000, height: 1500 },
  tall:       { width: 1000, height: 1600 },
  square_ish: { width: 1080, height: 1350 },
  square:     { width: 1000, height: 1000 },
};

module.exports = {
  FONT_PRESETS,
  OVERLAY_TYPES,
  COLOR_PALETTES,
  TEMPLATE_FAMILIES,
  PIN_SIZES,
};
