/**
 * Enhanced Template Configs
 * Additions:
 * - Locked color palette presets per template
 * - Gradient fade overlay type
 * - Card edge treatment presets (hard / soft / feathered / shadow-only)
 * - Per-font letter-spacing baked into presets
 */

// ─── Font Presets ─────────────────────────────────────────────────────────────
const FONT_PRESETS = {
  manrope_inter: {
    heading: "'Manrope', sans-serif",
    body:    "'Inter', sans-serif",
    headingWeight: 800,
    bodyWeight:    400,
    headingTracking: '-0.02em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.10em',
  },
  playfair_inter: {
    heading: "'Playfair Display', serif",
    body:    "'Inter', sans-serif",
    headingWeight: 700,
    bodyWeight:    400,
    headingTracking: '-0.03em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.08em',
  },
  jakarta_dm: {
    heading: "'Plus Jakarta Sans', sans-serif",
    body:    "'DM Sans', sans-serif",
    headingWeight: 700,
    bodyWeight:    400,
    headingTracking: '-0.01em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.10em',
  },
  cormorant_manrope: {
    heading: "'Cormorant Garamond', serif",
    body:    "'Manrope', sans-serif",
    headingWeight: 600,
    bodyWeight:    500,
    headingTracking: '0.01em',
    bodyTracking:    '0em',
    altCapsTracking: '0.12em',
  },
  outfit_inter: {
    heading: "'Outfit', sans-serif",
    body:    "'Inter', sans-serif",
    headingWeight: 800,
    bodyWeight:    400,
    headingTracking: '-0.02em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.10em',
  },
  anton_inter: {
    heading: "'Anton', sans-serif",
    body:    "'Inter', sans-serif",
    headingWeight: 400,
    bodyWeight:    500,
    headingTracking: '0em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.08em',
  },
  oswald_inter: {
    heading: "'Oswald', sans-serif",
    body:    "'Inter', sans-serif",
    headingWeight: 700,
    bodyWeight:    500,
    headingTracking: '0em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.10em',
  },
  bebas_inter: {
    heading: "'Bebas Neue', sans-serif",
    body:    "'Inter', sans-serif",
    headingWeight: 400,
    bodyWeight:    500,
    headingTracking: '0.01em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.08em',
  },
  archivo_dm: {
    heading: "'Archivo Black', sans-serif",
    body:    "'DM Sans', sans-serif",
    headingWeight: 400,
    bodyWeight:    500,
    headingTracking: '-0.02em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.10em',
  },
  libre_inter: {
    heading: "'Libre Baskerville', serif",
    body:    "'Inter', sans-serif",
    headingWeight: 700,
    bodyWeight:    400,
    headingTracking: '-0.02em',
    bodyTracking:    '-0.01em',
    altCapsTracking: '0.08em',
  },
};

// ─── Color Palette Presets ────────────────────────────────────────────────────
const COLOR_PALETTES = {
  pure_white:  { bg: '#ffffff',  text: '#111111', sub: '#444444', accent: '#111111' },
  off_white:   { bg: '#FAFAF8',  text: '#1a1a1a', sub: '#555555', accent: '#1a1a1a' },
  warm_cream:  { bg: '#F5F0E8',  text: '#2d1b00', sub: '#6b4c2a', accent: '#4a3000' },
  dark_ink:    { bg: '#111111',  text: '#f5f5f0', sub: '#aaaaaa', accent: '#e8e8e0' },
  charcoal:    { bg: '#1a1a2e',  text: '#f0f0f5', sub: '#9090a8', accent: '#a78bfa' },
};

// ─── Overlay Types ────────────────────────────────────────────────────────────
const OVERLAY_TYPES = {
  none:               { type: 'none',    opacity: 0 },
  translucent_white:  { type: 'sheet',   bg: 'rgba(255,255,255,0.82)',  blur: '8px',  edge: 'soft',      radius: '4px' },
  cream_card:         { type: 'card',    bg: 'rgba(253,248,240,0.92)',  blur: '4px',  edge: 'soft',      radius: '12px' },
  lower_third:        { type: 'lower',   bg: 'rgba(255,255,255,0.90)',  blur: '6px',  edge: 'hard',      radius: '0px' },
  top_white_sheet:    { type: 'sheet',   bg: 'rgba(255,255,255,0.88)',  blur: '8px',  edge: 'hard',      radius: '0px' },
  white_veil:         { type: 'veil',    bg: 'rgba(255,255,255,0.20)',  blur: '0px',  edge: 'none',      radius: '0px', opacity: 0.20, fixedOpacity: true },
  black_veil:         { type: 'veil',    bg: 'rgba(0,0,0,0.28)',        blur: '0px',  edge: 'none',      radius: '0px', opacity: 0.28, fixedOpacity: true },
  outline_clear:      { type: 'outline', bg: 'rgba(255,255,255,0.06)',  blur: '0px',  edge: 'soft',      radius: '0px', opacity: 0.06, fixedOpacity: true },
  subtle_fade:        { type: 'fade',    bg: 'linear-gradient(to top, rgba(0,0,0,0.72) 0%, transparent 58%)', blur: '0px', edge: 'none' },
  corner_light_tl:    { type: 'fade',    bg: 'radial-gradient(circle at 0% 0%, rgba(255,255,255,0.92) 0%, rgba(255,255,255,0.62) 34%, rgba(255,255,255,0.00) 68%)', blur: '0px', edge: 'none' },
  corner_light_tr:    { type: 'fade',    bg: 'radial-gradient(circle at 100% 0%, rgba(255,255,255,0.92) 0%, rgba(255,255,255,0.62) 34%, rgba(255,255,255,0.00) 68%)', blur: '0px', edge: 'none' },
  corner_dark_bl:     { type: 'fade',    bg: 'radial-gradient(circle at 0% 100%, rgba(0,0,0,0.82) 0%, rgba(0,0,0,0.44) 36%, rgba(0,0,0,0.00) 70%)', blur: '0px', edge: 'none' },
  corner_dark_br:     { type: 'fade',    bg: 'radial-gradient(circle at 100% 100%, rgba(0,0,0,0.82) 0%, rgba(0,0,0,0.44) 36%, rgba(0,0,0,0.00) 70%)', blur: '0px', edge: 'none' },
  gradient_cream:     { type: 'fade',    bg: 'linear-gradient(to top, rgba(245,240,232,0.95) 0%, rgba(245,240,232,0.60) 40%, transparent 70%)', blur: '0px', edge: 'none' },
  gradient_dark:      { type: 'fade',    bg: 'linear-gradient(to top, rgba(0,0,0,0.88) 0%, rgba(0,0,0,0.45) 45%, transparent 72%)', blur: '0px', edge: 'none' },
  gradient_top:       { type: 'fade',    bg: 'linear-gradient(to bottom, rgba(0,0,0,0.65) 0%, rgba(0,0,0,0.20) 45%, transparent 70%)', blur: '0px', edge: 'none' },
  soft_panel:         { type: 'panel',   bg: 'rgba(255,255,255,0.75)',  blur: '12px', edge: 'soft',      radius: '20px' },
  dark_panel:         { type: 'panel',   bg: 'rgba(10,10,10,0.72)',     blur: '6px',  edge: 'soft',      radius: '16px' },
  luxury_cream:       { type: 'sheet',   bg: 'rgba(250,246,238,0.88)',  blur: '6px',  edge: 'feathered', radius: '0px' },
  side_block_light:    { type: 'side',    bg: 'linear-gradient(90deg, rgba(250,250,248,0.96) 0%, rgba(250,250,248,0.88) 72%, rgba(250,250,248,0.00) 100%)', blur: '0px', edge: 'none', radius: '0px' },
  side_block_right:    { type: 'side',    bg: 'linear-gradient(270deg, rgba(250,250,248,0.96) 0%, rgba(250,250,248,0.88) 72%, rgba(250,250,248,0.00) 100%)', blur: '0px', edge: 'none', radius: '0px' },
  statement_veil:      { type: 'fade',    bg: 'linear-gradient(135deg, rgba(0,0,0,0.82) 0%, rgba(0,0,0,0.42) 58%, rgba(0,0,0,0.72) 100%)', blur: '0px', edge: 'none', radius: '0px' },
  checklist_card:      { type: 'card',    bg: 'rgba(255,255,255,0.94)',  blur: '7px',  edge: 'soft',      radius: '14px' },
  number_panel:        { type: 'card',    bg: 'rgba(247,250,252,0.92)',  blur: '5px',  edge: 'soft',      radius: '12px' },
  dark_glass_gold:     { type: 'panel',   bg: 'rgba(7,10,13,0.78)',      blur: '14px', edge: 'soft',      radius: '18px' },
};

// ─── Template Families ────────────────────────────────────────────────────────
const TEMPLATE_FAMILIES = {

  upper_third_overlay: {
    id: 'upper_third_overlay',
    name: 'Upper Third Direct Overlay',
    description: 'Bold text placed in the upper third of the image',
    fontPreset: 'manrope_inter',
    overlay: 'top_white_sheet',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'upper',
    textAlign: 'left',
    maxTitleWidth: '75%',
    titleSizeMin: 38,
    titleSizeMax: 88,
    padding: { x: 60, y: 80 },
    textShadow: 'none',
    gradientOverlay: null,
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'top-right',
    suitableFor: ['clean_top', 'light_top', 'dark_top', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 48,
  },

  top_middle_headline: {
    id: 'top_middle_headline',
    name: 'Upper Third Center Overlay',
    description: 'Bold text centered in the upper third of the image',
    fontPreset: 'manrope_inter',
    overlay: 'top_white_sheet',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'upper-center',
    textAlign: 'center',
    maxTitleWidth: '75%',
    titleSizeMin: 38,
    titleSizeMax: 88,
    padding: { x: 60, y: 80 },
    textShadow: 'none',
    gradientOverlay: null,
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['clean_top', 'light_top', 'dark_top', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 48,
  },

  veil_top_left: {
    id: 'veil_top_left',
    name: 'Soft Veil Top Left',
    description: 'Low-opacity full white veil with text in the top left',
    fontPreset: 'manrope_inter',
    overlay: 'white_veil',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'upper-left',
    textAlign: 'left',
    maxTitleWidth: '68%',
    titleSizeMin: 38,
    titleSizeMax: 82,
    padding: { x: 70, y: 88 },
    textShadow: 'none',
    gradientOverlay: null,
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'top-left',
    suitableFor: ['clean_top', 'light_top', 'dark_top', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 48,
  },

  veil_top_center: {
    id: 'veil_top_center',
    name: 'Soft Veil Top Center',
    description: 'Low-opacity full white veil with text centered near the top',
    fontPreset: 'manrope_inter',
    overlay: 'white_veil',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'upper-center',
    textAlign: 'center',
    maxTitleWidth: '72%',
    titleSizeMin: 38,
    titleSizeMax: 82,
    padding: { x: 70, y: 88 },
    textShadow: 'none',
    gradientOverlay: null,
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['clean_top', 'light_top', 'dark_top', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 48,
  },

  veil_center: {
    id: 'veil_center',
    name: 'Soft Veil Center',
    description: 'Low-opacity full white veil with centered text',
    fontPreset: 'outfit_inter',
    overlay: 'white_veil',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '72%',
    titleSizeMin: 42,
    titleSizeMax: 86,
    padding: { x: 80, y: 80 },
    textShadow: 'none',
    gradientOverlay: null,
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['minimal', 'gradient', 'any'],
    avoidWhen: ['text_heavy'],
    safeMinPaddingPx: 72,
  },

  center_white_sheet: {
    id: 'center_white_sheet',
    name: 'Center Translucent White Sheet',
    description: 'Frosted glass card centered on image',
    fontPreset: 'jakarta_dm',
    overlay: 'translucent_white',
    colorPalette: 'pure_white',
    textColor: '#1a1a2e',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '80%',
    titleSizeMin: 42,
    titleSizeMax: 78,
    padding: { x: 60, y: 50 },
    textShadow: 'none',
    gradientOverlay: null,
    overlayWidth: '78%',
    overlayPaddingX: 48,
    overlayPaddingY: 52,
    showHRule: true,
    titleScale: 1.06,
    ctaStyle: 'pill',
    badgePosition: 'overlay-top',
    suitableFor: ['any', 'busy_center', 'colorful'],
    avoidWhen: [],
    safeMinPaddingPx: 48,
  },

  lower_third_card: {
    id: 'lower_third_card',
    name: 'Lower Third White Card',
    description: 'Clean card anchored to the bottom third',
    fontPreset: 'jakarta_dm',
    overlay: 'lower_third',
    colorPalette: 'off_white',
    textColor: '#111827',
    textPosition: 'lower',
    textAlign: 'left',
    maxTitleWidth: '85%',
    titleSizeMin: 40,
    titleSizeMax: 76,
    padding: { x: 48, y: 44 },
    textShadow: 'none',
    gradientOverlay: null,
    overlayHeight: '42%',
    showHRule: true,
    titleScale: 1.10,
    ctaStyle: 'pill',
    badgePosition: 'card-top',
    suitableFor: ['clean_top', 'any'],
    avoidWhen: ['busy_bottom'],
    safeMinPaddingPx: 48,
  },

  left_editorial_column: {
    id: 'left_editorial_column',
    name: 'Left Editorial Column',
    description: 'Vertical card on the left with editorial styling',
    fontPreset: 'cormorant_manrope',
    overlay: 'cream_card',
    colorPalette: 'warm_cream',
    textColor: '#1c1205',
    textPosition: 'left',
    textAlign: 'left',
    maxTitleWidth: '94%',
    titleSizeMin: 44,
    titleSizeMax: 76,
    padding: { x: 42, y: 48 },
    textShadow: 'none',
    gradientOverlay: null,
    columnWidth: '56%',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'column-top',
    suitableFor: ['clean_right', 'portrait_subjects', 'warm_tones'],
    avoidWhen: ['busy_left'],
    safeMinPaddingPx: 48,
  },

  floating_soft_panel: {
    id: 'floating_soft_panel',
    name: 'Floating Soft Panel',
    description: 'Glassmorphism floating panel with soft blur',
    fontPreset: 'outfit_inter',
    overlay: 'soft_panel',
    colorPalette: 'pure_white',
    textColor: '#0f172a',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '74%',
    titleSizeMin: 38,
    titleSizeMax: 72,
    padding: { x: 52, y: 48 },
    textShadow: 'none',
    gradientOverlay: null,
    panelWidth: '74%',
    panelRadius: '24px',
    showHRule: false,
    titleScale: 1.05,
    ctaStyle: 'pill',
    badgePosition: 'panel-top',
    suitableFor: ['any', 'gradient', 'abstract'],
    avoidWhen: [],
    safeMinPaddingPx: 48,
  },

  premium_article_cover: {
    id: 'premium_article_cover',
    name: 'Premium Article Cover',
    description: 'Magazine-style full cover with dark gradient fade',
    fontPreset: 'playfair_inter',
    overlay: 'gradient_dark',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'lower',
    textAlign: 'left',
    maxTitleWidth: '80%',
    titleSizeMin: 42,
    titleSizeMax: 76,
    padding: { x: 64, y: 76 },
    textShadow: '0 2px 16px rgba(0,0,0,0.4)',
    gradientOverlay: null,
    showHRule: true,
    coverLiftPx: 58,
    lineHeightBoost: 0.04,
    titleScale: 1.08,
    ctaStyle: 'pill',
    badgePosition: 'top-left',
    suitableFor: ['dark_bottom', 'any'],
    avoidWhen: ['light_bottom'],
    safeMinPaddingPx: 48,
  },

  soft_magazine: {
    id: 'soft_magazine',
    name: 'Soft Magazine Layout',
    description: 'Airy layout with gradient cream overlay',
    fontPreset: 'cormorant_manrope',
    overlay: 'gradient_cream',
    colorPalette: 'warm_cream',
    textColor: '#2d1b00',
    textPosition: 'lower-center',
    textAlign: 'center',
    maxTitleWidth: '82%',
    titleSizeMin: 38,
    titleSizeMax: 68,
    padding: { x: 60, y: 56 },
    textShadow: 'none',
    gradientOverlay: null,
    overlayHeight: '48%',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'overlay-center-top',
    suitableFor: ['warm_tones', 'desk', 'linen', 'marble'],
    avoidWhen: ['dark_tones'],
    safeMinPaddingPx: 48,
  },

  luxury_desk_headline: {
    id: 'luxury_desk_headline',
    name: 'Luxury Desk Headline',
    description: 'Dark panel headline for luxury/editorial aesthetic',
    fontPreset: 'manrope_inter',
    overlay: 'dark_panel',
    colorPalette: 'dark_ink',
    textColor: '#f5f0e8',
    textPosition: 'upper-left',
    textAlign: 'left',
    maxTitleWidth: '78%',
    titleSizeMin: 40,
    titleSizeMax: 72,
    padding: { x: 52, y: 64 },
    textShadow: '0 2px 12px rgba(0,0,0,0.3)',
    gradientOverlay: null,
    panelWidth: '78%',
    panelRadius: '16px',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'panel-top-right',
    suitableFor: ['dark_luxury', 'dark_tones', 'marble', 'wood'],
    avoidWhen: ['light_tones'],
    safeMinPaddingPx: 48,
  },

  minimalist_gradient_poster: {
    id: 'minimalist_gradient_poster',
    name: 'Minimalist Gradient Poster',
    description: 'Centered bold text over a subtle gradient veil',
    fontPreset: 'outfit_inter',
    overlay: 'none',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '68%',
    titleSizeMin: 42,
    titleSizeMax: 78,
    padding: { x: 80, y: 80 },
    textShadow: '0 4px 40px rgba(0,0,0,0.5)',
    gradientOverlay: 'linear-gradient(135deg, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0.15) 50%, rgba(0,0,0,0.45) 100%)',
    showHRule: false,
    lineHeightBoost: 0.07,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['gradient', 'abstract', 'minimal', 'texture'],
    avoidWhen: [],
    safeMinPaddingPx: 80,
  },

  gradient_editorial: {
    id: 'gradient_editorial',
    name: 'Gradient Editorial',
    description: 'Lower gradient fade — the single most-used premium Pinterest technique',
    fontPreset: 'playfair_inter',
    overlay: 'gradient_dark',
    colorPalette: null,
    textColor: '#FAFAF8',
    textPosition: 'lower',
    textAlign: 'left',
    maxTitleWidth: '80%',
    titleSizeMin: 42,
    titleSizeMax: 80,
    padding: { x: 84, y: 84 },
    textShadow: '0 2px 20px rgba(0,0,0,0.45)',
    gradientOverlay: null,
    showHRule: true,
    coverLiftPx: 24,
    titleScale: 1.06,
    ctaStyle: 'pill',
    badgePosition: 'top-left',
    suitableFor: ['any', 'dark_bottom', 'portrait_subjects'],
    avoidWhen: [],
    safeMinPaddingPx: 48,
  },

  split_hero_editorial: {
    id: 'split_hero_editorial',
    name: 'Split Hero Editorial',
    description: 'Editorial side block for images with a clean side or clear subject split',
    fontPreset: 'manrope_inter',
    overlay: 'side_block_light',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'left',
    textAlign: 'left',
    maxTitleWidth: '54%',
    titleSizeMin: 30,
    titleSizeMax: 56,
    padding: { x: 56, y: 72 },
    textShadow: 'none',
    gradientOverlay: null,
    sideWidth: '58%',
    showHRule: true,
    titleScale: 0.92,
    ctaStyle: 'pill',
    badgePosition: 'column-top',
    suitableFor: ['clean_left', 'clean_right', 'portrait_subjects', 'any'],
    avoidWhen: ['busy_left'],
    safeMinPaddingPx: 48,
  },

  split_hero_right: {
    id: 'split_hero_right',
    name: 'Right Split Editorial',
    description: 'Editorial side block on the right for images with clean right space',
    fontPreset: 'manrope_inter',
    overlay: 'side_block_right',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'right',
    textAlign: 'left',
    maxTitleWidth: '54%',
    titleSizeMin: 30,
    titleSizeMax: 56,
    padding: { x: 56, y: 72 },
    textShadow: 'none',
    gradientOverlay: null,
    sideWidth: '58%',
    showHRule: true,
    titleScale: 0.92,
    ctaStyle: 'pill',
    badgePosition: 'column-top',
    suitableFor: ['clean_right', 'portrait_subjects', 'any'],
    avoidWhen: ['busy_right'],
    safeMinPaddingPx: 48,
  },

  bold_top_right: {
    id: 'bold_top_right',
    name: 'Bold Top Right',
    description: 'Large bold headline tucked into the top-right safe zone',
    fontPreset: 'anton_inter',
    overlay: 'black_veil',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'upper-right',
    textAlign: 'right',
    maxTitleWidth: '64%',
    titleSizeMin: 46,
    titleSizeMax: 96,
    padding: { x: 72, y: 88 },
    textShadow: '0 4px 24px rgba(0,0,0,0.48)',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: false,
    titleScale: 1.08,
    ctaStyle: 'pill',
    badgePosition: 'top-right',
    suitableFor: ['clean_top', 'dark_top', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 64,
  },

  bold_middle_left: {
    id: 'bold_middle_left',
    name: 'Bold Middle Left',
    description: 'Bold text block centered vertically on the left',
    fontPreset: 'oswald_inter',
    overlay: 'black_veil',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'middle-left',
    textAlign: 'left',
    maxTitleWidth: '62%',
    titleSizeMin: 44,
    titleSizeMax: 88,
    padding: { x: 76, y: 76 },
    textShadow: '0 4px 24px rgba(0,0,0,0.48)',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: false,
    titleScale: 1.04,
    ctaStyle: 'pill',
    badgePosition: 'top-left',
    suitableFor: ['clean_left', 'dark_tones', 'any'],
    avoidWhen: ['busy_left'],
    safeMinPaddingPx: 64,
  },

  bold_middle_right: {
    id: 'bold_middle_right',
    name: 'Bold Middle Right',
    description: 'Bold text block centered vertically on the right',
    fontPreset: 'oswald_inter',
    overlay: 'black_veil',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'middle-right',
    textAlign: 'right',
    maxTitleWidth: '62%',
    titleSizeMin: 44,
    titleSizeMax: 88,
    padding: { x: 76, y: 76 },
    textShadow: '0 4px 24px rgba(0,0,0,0.48)',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: false,
    titleScale: 1.04,
    ctaStyle: 'pill',
    badgePosition: 'top-right',
    suitableFor: ['clean_right', 'dark_tones', 'any'],
    avoidWhen: ['busy_right'],
    safeMinPaddingPx: 64,
  },

  bold_bottom_center: {
    id: 'bold_bottom_center',
    name: 'Bold Bottom Center',
    description: 'Bold centered headline anchored near the bottom',
    fontPreset: 'archivo_dm',
    overlay: 'subtle_fade',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'lower-center',
    textAlign: 'center',
    maxTitleWidth: '76%',
    titleSizeMin: 44,
    titleSizeMax: 92,
    padding: { x: 80, y: 86 },
    textShadow: '0 4px 24px rgba(0,0,0,0.45)',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: false,
    titleScale: 1.08,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['dark_bottom', 'any'],
    avoidWhen: ['busy_bottom'],
    safeMinPaddingPx: 64,
  },

  black_veil_top: {
    id: 'black_veil_top',
    name: 'Black Veil Top',
    description: 'Low-opacity black veil with top-centered white text',
    fontPreset: 'bebas_inter',
    overlay: 'black_veil',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'upper-center',
    textAlign: 'center',
    maxTitleWidth: '72%',
    titleSizeMin: 48,
    titleSizeMax: 100,
    padding: { x: 74, y: 86 },
    textShadow: '0 4px 20px rgba(0,0,0,0.42)',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: false,
    titleScale: 1.12,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['light_tones', 'clean_top', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 64,
  },

  black_veil_center: {
    id: 'black_veil_center',
    name: 'Black Veil Center',
    description: 'Low-opacity black veil with centered white text',
    fontPreset: 'anton_inter',
    overlay: 'black_veil',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '72%',
    titleSizeMin: 48,
    titleSizeMax: 104,
    padding: { x: 80, y: 80 },
    textShadow: '0 5px 26px rgba(0,0,0,0.48)',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: false,
    titleScale: 1.12,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['minimal', 'light_tones', 'any'],
    avoidWhen: ['text_heavy'],
    safeMinPaddingPx: 72,
  },

  corner_light_top_left: {
    id: 'corner_light_top_left',
    name: 'Light Corner Top Left',
    description: 'Soft light corner fade with top-left text',
    fontPreset: 'jakarta_dm',
    overlay: 'corner_light_tl',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'upper-left',
    textAlign: 'left',
    maxTitleWidth: '62%',
    titleSizeMin: 38,
    titleSizeMax: 78,
    padding: { x: 68, y: 84 },
    textShadow: 'none',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'top-left',
    suitableFor: ['clean_top', 'light_tones', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 56,
  },

  corner_light_top_right: {
    id: 'corner_light_top_right',
    name: 'Light Corner Top Right',
    description: 'Soft light corner fade with top-right text',
    fontPreset: 'jakarta_dm',
    overlay: 'corner_light_tr',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'upper-right',
    textAlign: 'right',
    maxTitleWidth: '62%',
    titleSizeMin: 38,
    titleSizeMax: 78,
    padding: { x: 68, y: 84 },
    textShadow: 'none',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'top-right',
    suitableFor: ['clean_top', 'light_tones', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 56,
  },

  corner_dark_bottom_left: {
    id: 'corner_dark_bottom_left',
    name: 'Dark Corner Bottom Left',
    description: 'Dark corner fade with bottom-left white text',
    fontPreset: 'libre_inter',
    overlay: 'corner_dark_bl',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'lower-left',
    textAlign: 'left',
    maxTitleWidth: '66%',
    titleSizeMin: 38,
    titleSizeMax: 78,
    padding: { x: 72, y: 82 },
    textShadow: '0 3px 18px rgba(0,0,0,0.42)',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'top-left',
    suitableFor: ['dark_bottom', 'any'],
    avoidWhen: ['busy_bottom'],
    safeMinPaddingPx: 56,
  },

  corner_dark_bottom_right: {
    id: 'corner_dark_bottom_right',
    name: 'Dark Corner Bottom Right',
    description: 'Dark corner fade with bottom-right white text',
    fontPreset: 'libre_inter',
    overlay: 'corner_dark_br',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'lower-right',
    textAlign: 'right',
    maxTitleWidth: '66%',
    titleSizeMin: 38,
    titleSizeMax: 78,
    padding: { x: 72, y: 82 },
    textShadow: '0 3px 18px rgba(0,0,0,0.42)',
    gradientOverlay: null,
    contentStyle: 'direct',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'top-right',
    suitableFor: ['dark_bottom', 'any'],
    avoidWhen: ['busy_bottom'],
    safeMinPaddingPx: 56,
  },

  left_dark_column: {
    id: 'left_dark_column',
    name: 'Left Dark Column',
    description: 'Dark vertical column on the left with bold white text',
    fontPreset: 'archivo_dm',
    overlay: 'dark_panel',
    colorPalette: 'dark_ink',
    textColor: '#ffffff',
    textPosition: 'left',
    textAlign: 'left',
    maxTitleWidth: '92%',
    titleSizeMin: 38,
    titleSizeMax: 78,
    padding: { x: 54, y: 66 },
    textShadow: 'none',
    gradientOverlay: null,
    columnWidth: '52%',
    contentStyle: 'dark_column',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'column-top',
    suitableFor: ['clean_left', 'dark_tones', 'any'],
    avoidWhen: ['busy_left'],
    safeMinPaddingPx: 48,
  },

  right_dark_column: {
    id: 'right_dark_column',
    name: 'Right Dark Column',
    description: 'Dark vertical column on the right with bold white text',
    fontPreset: 'archivo_dm',
    overlay: 'dark_panel',
    colorPalette: 'dark_ink',
    textColor: '#ffffff',
    textPosition: 'right',
    textAlign: 'left',
    maxTitleWidth: '92%',
    titleSizeMin: 38,
    titleSizeMax: 78,
    padding: { x: 54, y: 66 },
    textShadow: 'none',
    gradientOverlay: null,
    columnWidth: '52%',
    contentStyle: 'dark_column_right',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'column-top',
    suitableFor: ['clean_right', 'dark_tones', 'any'],
    avoidWhen: ['busy_right'],
    safeMinPaddingPx: 48,
  },

  center_outline_box: {
    id: 'center_outline_box',
    name: 'Center Outline Box',
    description: 'Transparent outlined box centered on the image',
    fontPreset: 'oswald_inter',
    overlay: 'outline_clear',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '78%',
    titleSizeMin: 42,
    titleSizeMax: 86,
    padding: { x: 64, y: 64 },
    textShadow: '0 4px 24px rgba(0,0,0,0.52)',
    gradientOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.18) 0%, rgba(0,0,0,0.34) 100%)',
    contentStyle: 'outline_box',
    panelWidth: '78%',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'panel-top',
    suitableFor: ['minimal', 'any'],
    avoidWhen: [],
    safeMinPaddingPx: 64,
  },

  top_outline_box: {
    id: 'top_outline_box',
    name: 'Top Outline Box',
    description: 'Transparent outlined box near the top',
    fontPreset: 'oswald_inter',
    overlay: 'outline_clear',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'upper-center',
    textAlign: 'center',
    maxTitleWidth: '78%',
    titleSizeMin: 38,
    titleSizeMax: 80,
    padding: { x: 64, y: 76 },
    textShadow: '0 4px 24px rgba(0,0,0,0.52)',
    gradientOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.26) 0%, rgba(0,0,0,0.00) 58%)',
    contentStyle: 'outline_top',
    panelWidth: '78%',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'panel-top',
    suitableFor: ['clean_top', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 64,
  },

  bottom_outline_box: {
    id: 'bottom_outline_box',
    name: 'Bottom Outline Box',
    description: 'Transparent outlined box near the bottom',
    fontPreset: 'oswald_inter',
    overlay: 'outline_clear',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'lower-center',
    textAlign: 'center',
    maxTitleWidth: '78%',
    titleSizeMin: 38,
    titleSizeMax: 80,
    padding: { x: 64, y: 76 },
    textShadow: '0 4px 24px rgba(0,0,0,0.52)',
    gradientOverlay: 'linear-gradient(0deg, rgba(0,0,0,0.30) 0%, rgba(0,0,0,0.00) 58%)',
    contentStyle: 'outline_bottom',
    panelWidth: '78%',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'panel-top',
    suitableFor: ['dark_bottom', 'any'],
    avoidWhen: ['busy_bottom'],
    safeMinPaddingPx: 64,
  },

  giant_word_center: {
    id: 'giant_word_center',
    name: 'Giant Word Center',
    description: 'Oversized condensed type centered like a poster',
    fontPreset: 'bebas_inter',
    overlay: 'black_veil',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '86%',
    titleSizeMin: 58,
    titleSizeMax: 118,
    padding: { x: 70, y: 70 },
    textShadow: '0 5px 26px rgba(0,0,0,0.48)',
    gradientOverlay: null,
    contentStyle: 'giant_word',
    showHRule: false,
    titleScale: 1.18,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['minimal', 'gradient', 'abstract', 'any'],
    avoidWhen: ['text_heavy'],
    safeMinPaddingPx: 72,
  },

  quote_overlay: {
    id: 'quote_overlay',
    name: 'Quote Overlay',
    description: 'Editorial quote-style layout with large quotation mark',
    fontPreset: 'libre_inter',
    overlay: 'white_veil',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '78%',
    titleSizeMin: 36,
    titleSizeMax: 72,
    padding: { x: 78, y: 78 },
    textShadow: 'none',
    gradientOverlay: null,
    contentStyle: 'quote',
    showHRule: false,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['minimal', 'warm_tones', 'any'],
    avoidWhen: ['text_heavy'],
    safeMinPaddingPx: 64,
  },

  vertical_strip_left: {
    id: 'vertical_strip_left',
    name: 'Vertical Strip Left',
    description: 'Narrow light strip on the left with stacked editorial text',
    fontPreset: 'manrope_inter',
    overlay: 'side_block_light',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'left',
    textAlign: 'left',
    maxTitleWidth: '96%',
    titleSizeMin: 30,
    titleSizeMax: 62,
    padding: { x: 38, y: 64 },
    textShadow: 'none',
    gradientOverlay: null,
    sideWidth: '36%',
    contentStyle: 'vertical_strip_left',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'column-top',
    suitableFor: ['clean_left', 'portrait_subjects', 'any'],
    avoidWhen: ['busy_left'],
    safeMinPaddingPx: 48,
  },

  vertical_strip_right: {
    id: 'vertical_strip_right',
    name: 'Vertical Strip Right',
    description: 'Narrow light strip on the right with stacked editorial text',
    fontPreset: 'manrope_inter',
    overlay: 'side_block_right',
    colorPalette: 'off_white',
    textColor: '#111111',
    textPosition: 'right',
    textAlign: 'left',
    maxTitleWidth: '96%',
    titleSizeMin: 30,
    titleSizeMax: 62,
    padding: { x: 38, y: 64 },
    textShadow: 'none',
    gradientOverlay: null,
    sideWidth: '36%',
    contentStyle: 'vertical_strip_right',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'column-top',
    suitableFor: ['clean_right', 'portrait_subjects', 'any'],
    avoidWhen: ['busy_right'],
    safeMinPaddingPx: 48,
  },

  bold_statement_poster: {
    id: 'bold_statement_poster',
    name: 'Bold Statement Poster',
    description: 'Large punchy statement for short viral-style claims',
    fontPreset: 'outfit_inter',
    overlay: 'statement_veil',
    colorPalette: null,
    textColor: '#ffffff',
    textPosition: 'center',
    textAlign: 'center',
    maxTitleWidth: '78%',
    titleSizeMin: 52,
    titleSizeMax: 96,
    padding: { x: 72, y: 72 },
    textShadow: '0 6px 34px rgba(0,0,0,0.48)',
    gradientOverlay: null,
    showHRule: false,
    titleScale: 1.12,
    lineHeightBoost: 0.02,
    ctaStyle: 'pill',
    badgePosition: 'top-center',
    suitableFor: ['minimal', 'gradient', 'abstract', 'dark_tones'],
    avoidWhen: ['text_heavy'],
    safeMinPaddingPx: 72,
  },

  checklist_card: {
    id: 'checklist_card',
    name: 'Checklist Card',
    description: 'Saveable card format for 3-5 checklist-style takeaways',
    fontPreset: 'jakarta_dm',
    overlay: 'checklist_card',
    colorPalette: 'pure_white',
    textColor: '#111827',
    textPosition: 'center',
    textAlign: 'left',
    maxTitleWidth: '86%',
    titleSizeMin: 34,
    titleSizeMax: 70,
    padding: { x: 56, y: 56 },
    textShadow: 'none',
    gradientOverlay: 'linear-gradient(180deg, rgba(255,255,255,0.10) 0%, rgba(0,0,0,0.16) 100%)',
    panelWidth: '82%',
    panelRadius: '14px',
    contentStyle: 'checklist',
    showHRule: true,
    titleScale: 1.08,
    ctaStyle: 'pill',
    badgePosition: 'panel-top',
    suitableFor: ['any', 'busy_center', 'light_tones'],
    avoidWhen: [],
    safeMinPaddingPx: 48,
  },

  numbered_list_feature: {
    id: 'numbered_list_feature',
    name: 'Numbered List Feature',
    description: 'Large number lockup for listicle and how-to pins',
    fontPreset: 'manrope_inter',
    overlay: 'number_panel',
    colorPalette: 'off_white',
    textColor: '#0f172a',
    textPosition: 'lower',
    textAlign: 'left',
    maxTitleWidth: '78%',
    titleSizeMin: 38,
    titleSizeMax: 76,
    padding: { x: 56, y: 56 },
    textShadow: 'none',
    gradientOverlay: null,
    contentStyle: 'numbered',
    overlayHeight: '46%',
    showHRule: false,
    titleScale: 1.08,
    ctaStyle: 'pill',
    badgePosition: 'card-top',
    suitableFor: ['any', 'clean_top', 'dark_bottom'],
    avoidWhen: ['busy_bottom'],
    safeMinPaddingPx: 48,
  },

  top_number_sheet: {
    id: 'top_number_sheet',
    name: 'Top Number Sheet',
    description: 'Wide translucent top sheet with separated large number and bold title',
    fontPreset: 'manrope_inter',
    overlay: 'top_white_sheet',
    colorPalette: 'off_white',
    textColor: '#0f172a',
    textPosition: 'upper',
    textAlign: 'left',
    maxTitleWidth: '78%',
    titleSizeMin: 40,
    titleSizeMax: 76,
    padding: { x: 56, y: 56 },
    textShadow: 'none',
    gradientOverlay: null,
    contentStyle: 'numbered_top',
    overlayHeight: '42%',
    showHRule: false,
    titleScale: 1.05,
    ctaStyle: 'pill',
    badgePosition: 'card-top',
    suitableFor: ['clean_top', 'light_tones', 'any'],
    avoidWhen: ['busy_top'],
    safeMinPaddingPx: 48,
  },

  dark_glass_finance: {
    id: 'dark_glass_finance',
    name: 'Dark Glass Finance',
    description: 'Dark glass card with warm premium accent for finance and wealth content',
    fontPreset: 'playfair_inter',
    overlay: 'dark_glass_gold',
    colorPalette: 'dark_ink',
    textColor: '#f8efe0',
    textPosition: 'center',
    textAlign: 'left',
    maxTitleWidth: '84%',
    titleSizeMin: 40,
    titleSizeMax: 76,
    padding: { x: 58, y: 60 },
    textShadow: '0 2px 18px rgba(0,0,0,0.45)',
    gradientOverlay: 'linear-gradient(160deg, rgba(0,0,0,0.32) 0%, rgba(0,0,0,0.08) 52%, rgba(0,0,0,0.46) 100%)',
    panelWidth: '80%',
    panelRadius: '18px',
    accentColor: '#d8b46a',
    showHRule: true,
    ctaStyle: 'pill',
    badgePosition: 'panel-top-right',
    suitableFor: ['dark_luxury', 'dark_tones', 'marble', 'wood'],
    avoidWhen: ['light_tones'],
    safeMinPaddingPx: 48,
  },
};

// ─── Pin Sizes ────────────────────────────────────────────────────────────────
const PIN_SIZES = {
  standard:   { width: 1000, height: 1500 },
  tall:       { width: 1000, height: 1600 },
  square_ish: { width: 1080, height: 1350 },
  square:     { width: 1000, height: 1000 },
};

module.exports = {
  FONT_PRESETS,
  OVERLAY_TYPES,
  COLOR_PALETTES,
  TEMPLATE_FAMILIES,
  PIN_SIZES,
};
